### ISSUE TITLE
Реализовать поиск карт и пользователей

### ISSUE THREAD

**Issue by Prifiz** [Prifiz/NC_SSAU_2015_16#10]
Нужен механизм поиска  по пользователям:
1. Выдавать список пользователей, содержащих введенную в поле поиска подстроку
2. Выдавать список пользователей, соответствующих введенному в поле поиска регулярному выражению.
Поиск по каждой сущности - это отдельный поиск. Надо подумать, как это сделать удобно с точки зрения юзера.

**Comment by Kitovsky** [comment]
С пользователем вроде разобрался. Правда только для регулярки. С подстрокой, как я понимаю, надо отдельное окошко делать(или какую то галочку водить для перехода на регулярку)

**Comment by Prifiz** [comment]
Обсудили подробности на встрече

**Comment by Kitovsky** [comment]
Поиск пользователей сделан. Осталось прикрутить его к графичеакой оболочке.

**Comment by Kitovsky** [comment]
Прикрутил к графической части. Добавил галку выбора поиска по регулярным выражениям или по подстроке.
