### ISSUE TITLE
Правки в классах сущностей

### ISSUE THREAD

**Issue by Prifiz** [Prifiz/NC_SSAU_2015_16#11]
Правка класса Initials(изменение названия и полей)
Настройка работы с датой 
Доработка методов equals 
Корректировка использования гетеров(местами лишние) 
Исправление хэш-кода
Настройка вложенных подпакетов
Исправление конструкторов в adress

**Comment by OlgaMoss** [comment]
Дату решила не изменять, оставить то, что было при первом показе.
Все остальные недочеты поправила.

**Comment by Prifiz** [comment]
Ок
