### ISSUE TITLE
LogIn -переименовать в  LogInFrame. и в нем же переименовать переменную

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#110]
LogIn log
Не надо называть эту переменную так же, как и поле класса. Запутаетесь назовите уж login
LogIn - это фрейм. Вот и пусть называется LogInFrame. Зато будет сразу понятно, что это не простой класс, а форма

**Comment by Morgan163** [comment]
фрейм переименован

**Comment by Kitovsky** [comment]
Переименовал переменную.
