### ISSUE TITLE
Закрывать Классы вью

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#113]
Надо не прятать, а закрывать ее с концами
private void backButtonActionPerformed(java.awt.event.ActionEvent evt) { 
// StartFrame start = new StartFrame(); 
// start.setVisible(true); 
this.setVisible(false); 
}

**Comment by Morgan163** [comment]
Это не только с Rules, а все фреймы так

**Comment by Morgan163** [comment]
теперь не setVisible(false), а
this.dispose();
