### ISSUE TITLE
Организуйте последовательную передачу сообщения

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#119]
Организуйте последовательную передачу сообщения: view -> промежуточная сущность -> посылка на сервер
Иначе у вас механизм обмена данными с серваком очень жестко привязан к форме. dataE.write(jComboBox.getSelectedItem().toString());
А вот тут вы явно перемешали view и логику

**Comment by Kitovsky** [comment]
Сделано через XML
