### ISSUE TITLE
public class Counter изменить на что-то из стандартного пакета

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#122]
public class Counter
А пробовали искать реализацию похожей штуки в стандартных пакетах?
Может помог бы Iterator?

**Comment by Morgan163** [comment]
Возможно неправильно назвал. Мне нужен был просто объект счетчик...

**Comment by Prifiz** [comment]
А зачем для этого вообще объект? Переменной не удастся обойтись?

**Comment by Morgan163** [comment]
Чтобы передать ссылку на него

**Comment by Morgan163** [comment]
Оставляем)
