### ISSUE TITLE
 sql-скрипты [Оля]

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#126]
Написать sql-скрипты по созданию и удалению базы данных и всех таблиц (каждый скрипт в отдельном .sql-файле). Протестировать каждый скрипт в среде Postgre-sql. Организовать скрипты так, чтобы не пришлось вручную вызывать кучу разных скриптов: там, где требуется, прописать вызов одного скрипта из другого.

**Comment by Kitovsky** [comment]
Прописать Insert`ы. Прописать drop`ы для таблиц.

**Comment by OlgaMoss** [comment]
исправила Creatы., Прописала dropы и Insertы
