### ISSUE TITLE
sql-скрипты [Дима]

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#127]
Написать sql-скрипты по созданию и удалению базы данных и всех таблиц (каждый скрипт в отдельном .sql-файле). Протестировать каждый скрипт в среде Postgre-sql. Организовать скрипты так, чтобы не пришлось вручную вызывать кучу разных скриптов: там, где требуется, прописать вызов одного скрипта из другого.

**Comment by Kitovsky** [comment]
Прописать Insert`ы. Прописать drop`ы для таблиц.

**Comment by Prifiz** [comment]
Это уже можно закрыть
