### ISSUE TITLE
хранимой процедуре на PostgreSQL [Андрей]

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#132]
каждому придумать и написать по одной хранимой процедуре на PostgreSQL. Потом на встрече обосновать, почему именно для этой цели используется хранимая процедура и какая в этом конкретном случае от нее выгода.
Ну естественно хранимые процедуры должны быть для вашей структуры БД

**Comment by Morgan163** [comment]
отмена
