### ISSUE TITLE
Та ли карта? "защита от китайца"

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#137]
Добавить проверку на то, что может ли вообще клиент положить такую карту (есть ли она в руке)
возможный вариант решения: представлять карты по ID (присвоить каждой карте в колоде, так как их количество известно самого начала)

**Comment by Morgan163** [comment]
Защита от китайца оказывается есть:DD Просто в таком случае вылетела бы ошибка и все сломалось. Поправил

**Comment by Prifiz** [comment]
Не забываем привязывать иши к milestone-ам
