### ISSUE TITLE
Сохранение и загрузка данных

### ISSUE THREAD

**Issue by Prifiz** [Prifiz/NC_SSAU_2015_16#15]
В системе должна быть кнопка, при нажатии которой все заполненные данные сохраняются в виде сериализованных объектов в файл (для каждого списка объектов свой файл, т.е. будет отдельный файл для списка всех карт, отдельный для списка всех юзеров и т.п.)
Плюс сохранение должно автоматически выполняться при выходе из программы.
При входе в программу система должна проверять, есть ли сериализованные файлы с сохраненными данными. Если есть, автоматически подгружать (десериализовать) их. Если файлов нет или случилась ошибка при подгрузке, выводить пользователю ненавязчивое сообщение и дать продолжать работу, т.е. не падать.

**Comment by OlgaMoss** [comment]
Кнопки пока нет
десерилизация происходит в начале, серилизация при закрытии фреймов

**Comment by Prifiz** [comment]
В принципе можно закрывать ишу. Кнопку можно впилить в любое время при необходимости.
