### ISSUE TITLE
Поддержка автоинкремента в таблицах

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#150]
Реализовать поддержку автоинкремента в таблицах.

**Comment by Morgan163** [comment]
сделано с помощью последовательности SEQUENCE

**Comment by Prifiz** [comment]
Посмотрите еще тут: http://www.tutorialspoint.com/postgresql/postgresql_using_autoincrement.htm
Помимо sequence-ов, есть еще и встроенные средства СУБД, использовать которые предпочтительнее.
