### ISSUE TITLE
Отмена регистрации

### ISSUE THREAD

**Issue by klyaba** [Prifiz/NC_SSAU_2015_16#18]
Создать кнопку отмены регистрации и возврата к предыдущему фрейму

**Comment by OlgaMoss** [comment]
предлагаю эту ишью оставить на следующий раз
планирую (не на этой недели) переписать этот фрейм, чтобы он выгладил более красивым

**Comment by Prifiz** [comment]
Да, давай перенесем

**Comment by OlgaMoss** [comment]
Кнопку сделала
