### ISSUE TITLE
Сделать сериализацию через XML.

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#33]

**Comment by Prifiz** [comment]
Сюда же приложить формат xml-файла. Лучше в виде xsd.
Плюс описать, какие данные будут храниться в файле и где будет располагаться сам файл.

**Comment by OlgaMoss** [comment]
Сериализация реализуется через технологию Jaxb
для маршализации даты класса LocalDate используется специальный класс-адаптер
хранимые данные - это персональные данные пользователя
Они хранятся в папке resources
