### ISSUE TITLE
Исправить фреймы

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#41]
Сделать одинаковый вид компонентов: поправить размер (сделать их одинаковыми), расположение, чтобы они были одинаково расположены относительно друг от друга. Избавить от автоматически прописанного кода проектировщика NetBeans'а

**Comment by Prifiz** [comment]
Каких компонентов? О каких фреймах речь? Что не так?
Это должно быть описано, чтобы потом понимать, что конкретно в этой ише сделано
