### ISSUE TITLE
реализовать синглтон(если надо)

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#42]
Пройтись по коду, проанализировать, где было бы уместно применить singleton, и в случае необходимости использовать его.

**Comment by Prifiz** [comment]
Из названия ничего не понятно.
Это задачка на исследование и рефакторинг кода. Т.е. нужно написать, что надо пройтись по коду, проанализировать, где было бы уместно применить singleton, и в случае необходимости это сделать.

**Comment by Morgan163** [comment]
Везде, где требуется, реализован
