### ISSUE TITLE
В геймплее: не убирается радио-кнопка. Исправить ошибку.

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#43]

**Comment by Prifiz** [comment]
Bug обычно описывается по следующей схеме:
1. Как воспроизвести ошибку, т.е. пошагово что нужно сделать.
2. Наблюдаемое поведение
3. Ожидаемое поведение

**Comment by Morgan163** [comment]
1. Чтобы воспроизвести ошибку нужно:
     В ситуации, когда у игрока осталось 2 карты, выбрать первую карту и положить на стол.
2. Карта не удаляется с панели, так как исключение возникает раньше, но удаляется из buttonGroup, поэтому ведет себя как отдельная кнопка.
3. Кнопка должна удалится с панели и последняя кнопка должна стать активной.

**Comment by Morgan163** [comment]
Баг исправлен. Теперь после совершения хода, кнопки автоматически не активируются. Если никакая кнопка не выбрана, выскакивает сообщение.
