### ISSUE TITLE
создание ER-диаграммы

### ISSUE THREAD

**Issue by OlgaMoss** [Prifiz/NC_SSAU_2015_16#61]
1. почитать про ER-диаграммы
2. Продумать:
2.1 какие сущности (основные классы) из сервера, надо будет взять для создания диаграммы.
2.2 учесть нормализацию (либо 3НФ, либо 4НФ)
3. Организовать иерархическую, поддерживающую наследование структуру.

**Comment by Prifiz** [comment]
Эта иша должна относиться к ближайшему milestone-у
