### ISSUE TITLE
Правка имен пакетов

### ISSUE THREAD

**Issue by Prifiz** [Prifiz/NC_SSAU_2015_16#7]
Имена пакетов должны начинаться с нижнего регистра.
В случае необходимости нужно делать вложенную структуру пакетов для удобной навигации по коду.

**Comment by Kitovsky** [comment]
Сдделал нормальные имена и чуть изменил структуру. Загрузил как стартовую версию ,т.к. по функционалу ничего не изменилось

**Comment by Prifiz** [comment]
Пакет action надо вынести из user. Иначе ты ломаешь MVC. action - это controller, а user - это model.

**Comment by Kitovsky** [comment]
Поправил. Вынес action.
