### ISSUE TITLE
Сделать автоформатирование кода лесенкой

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#82]
Сделать автоформатирование кода лесенкой.

**Comment by Prifiz** [comment]
Можно вообще оставить эту ишу как вечную для всех.
ВСЕГДА ДЕЛАТЬ АВТОФОРМАТИРОВАНИЕ КОДА ЛЕСЕНКОЙ.
Можно поковыряться в настройках IDE, может вообще автоматом умеет это делать, даже без комбинации. Можно настроить, чтобы прямо перед push это делалось само.

**Comment by Kitovsky** [comment]
Посмотрел код-везде лесенкой. Думаю ишу можно закрыть.
