### ISSUE TITLE
Убрать XML из исходников

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#84]
Не должно быть в исходниках сохраненных xml-ников с вашими данными. Уж если хотите поставлять базы к приложению, то отдельно от исходников. Да так, чтобы их нужно было положить в строго указанное место. Если файлов в этом указанном месте нет, то ничего не должно падать. Должно выводиться сообщение, что в системе нет данных. Но это не мешает пойти и добавить данных (например, зарегиться)

**Comment by Kitovsky** [comment]
Я так понимаю, это потенциально в будущем. Ибо щас хотя бы для просмотра работоспособности они частично нужны.или я не прав?

**Comment by Morgan163** [comment]
Смотря как дела обстоят с таблицей... Они нужны вроде только для нее

**Comment by Prifiz** [comment]
Это не в будущем, а сейчас. Одна из причин креша при запуске из консоли - именно эти файлы.
Сделайте нормальную структуру каталогов и выдавайте в ней все что нужно.
Можете заюзать maven-resources-plugin для копирования файлов и создания нужной структуры каталогов.
Т.е. смысл такой: я выкачиваю исходники, запускаю mvn clean install - и у меня должна создаться папка distrib, из которой я смогу стандартной командой java -jar запустить клиент или сервер и начать игру.
Собственно, если надо запустить прогу на другой машине (например, еще один клиент), эта папка копируется на нужный комп и снова из нее запускается джарник.
Желательно делать отдельные поставки для клиента и сервера (чтобы клиенты случайно не получили всю базу с сервера)

**Comment by Morgan163** [comment]
сделано. у клиента остались только правила
