### ISSUE TITLE
 privateInformation добавить конструктор без параметров

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#87]
Вы делаете privateInformation = new PrivateInformation("", "", LocalDate.now());
Видно, что параметры стандартные. В таких случаях их не передают так явно, а делают для PrivateInformation конструктор без параметров, в котором внутри эти дефолтные значения присваиваются

**Comment by OlgaMoss** [comment]
в ServiceInfo, Address и PrivateInformation добавлены конструкторы без параметров по дефолтным значениям
