### ISSUE TITLE
Найти проблемы(вероятно с NPE связано) и исправить

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#89]
if (serviceInfo.getLogin().equals(user.serviceInfo.getLogin())) {
return true;
}
А тут проблему найти самостоятельно

**Comment by Prifiz** [comment]
Есть идеи, где и когда это упадет?

**Comment by OlgaMoss** [comment]
Нет проверки на null в сравнении
Упадет, когда сравниваешь с null'ом

**Comment by Prifiz** [comment]
Ага, верно.
Плюс, помимо проверки, лучше бы еще и заранее контролировать, чтобы login был не null

**Comment by OlgaMoss** [comment]
сделано
