### ISSUE TITLE
Вывод списка пользователей

### ISSUE THREAD

**Issue by Prifiz** [Prifiz/NC_SSAU_2015_16#9]
В программе должна быть функция вывода списка всех пользователей в форме таблицы. Нужно обратить внимание на архитектуру, т.к. вывод всех пользователей - это частный случай поиска.

**Comment by Morgan163** [comment]
Сделано отображение списка пользователей в виде таблицы. Реализовано изменение данных в самой таблице. Так же есть добавление пользователей.
