### ISSUE TITLE
Сделать возможность наследования от Admin

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#92]
Если уж у вас в классе Admin явно задаются значения всех полей, то подумайте: что если кто-то напишет класс, наследующий от Admin? Например, я захочу создать какого-нибудь вспомогательного админа
Будет два админа с полностью совпадающими полями.
Как одним небольшим исправлением от этого избавиться?
Явное задание полей админа переписывать нельзя

**Comment by Prifiz** [comment]
Есть идеи, как поправить?

**Comment by Morgan163** [comment]
Сделал класс Admin final
