### ISSUE TITLE
WorkWithFiles переименовать в FileHandler 

### ISSUE THREAD

**Issue by Kitovsky** [Prifiz/NC_SSAU_2015_16#97]
WorkWithFiles
	
Обычно так классы не называют
	
Класс создается либо когда надо хранить какую-то инфу (тогда его называют так же, как и хранимую сущность, например User). Либо когда надо реализовать какие-то операции. Тогда класс называют с суффиксом -or или -er (т.е. подчеркивают, что он исполнитель). Например, Comparator
	
В вашем случае лучше было бы назвать FileHandler или FileHelper

**Comment by OlgaMoss** [comment]
переименовала в FileHandler
